/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTARITM = 0;


  public String[] jjtNodeName = {
    "Aritm",
  };
}
/* JavaCC - OriginalChecksum=5a7ecadfda78e952db495bf65b898daf (do not edit this line) */
