/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD extends SimpleNode {
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9adadfa0a2e284aa78a0718d7a21462d (do not edit this line) */
