/* Generated By:JJTree: Do not edit this line. ASTASSIGN_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGN_ARRAY extends SimpleNode {
  public ASTASSIGN_ARRAY(int id) {
    super(id);
  }

  public ASTASSIGN_ARRAY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c61ca3f26b2adb8f7db125947a204f3 (do not edit this line) */
