/* Generated By:JJTree: Do not edit this line. ASTARGV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGV extends SimpleNode {
  public ASTARGV(int id) {
    super(id);
  }

  public ASTARGV(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e8b29d65817a429210e39043058fca4 (do not edit this line) */
