/* Generated By:JJTree: Do not edit this line. ASTARGUMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENTS extends SimpleNode {
  public ASTARGUMENTS(int id) {
    super(id);
  }

  public ASTARGUMENTS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e0daf6848adc1c86dcfc601abcd8945 (do not edit this line) */
