/* Generated By:JJTree: Do not edit this line. ASTArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgs extends SimpleNode {
  public ASTArgs(int id) {
    super(id);
  }

  public ASTArgs(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7fb97877e1dfc7443e65940d3973ec81 (do not edit this line) */
