/* Generated By:JJTree: Do not edit this line. ASTARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARRAY extends SimpleNode {
  public ASTARRAY(int id) {
    super(id);
  }

  public ASTARRAY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b90a0018ddc22ded6aa5ee6986aeb3c (do not edit this line) */
