/* Generated By:JJTree: Do not edit this line. ASTARGV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGV extends SimpleNode {
  public ASTARGV(int id) {
    super(id);
  }

  public ASTARGV(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=63d9b2b982f7f11dc7bacef139f8dbff (do not edit this line) */
