/* Generated By:JJTree: Do not edit this line. ASTACCESS_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTACCESS_ARRAY extends SimpleNode {
  public ASTACCESS_ARRAY(int id) {
    super(id);
  }

  public ASTACCESS_ARRAY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b951aaefe3d3e2647e82c7d24c9509b (do not edit this line) */
