/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGN extends SimpleNode {
  public ASTASSIGN(int id) {
    super(id);
  }

  public ASTASSIGN(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=482229fe16e62ac833501230dccf81f8 (do not edit this line) */
