/* Generated By:JJTree: Do not edit this line. ASTBOOLEAN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOLEAN extends SimpleNode {
  public ASTBOOLEAN(int id) {
    super(id);
  }

  public ASTBOOLEAN(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69281956bc930efe54a7fb567ae021b7 (do not edit this line) */
