/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration_1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration_1 extends SimpleNode {
  public ASTClassDeclaration_1(int id) {
    super(id);
  }

  public ASTClassDeclaration_1(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46b7f04633b12ea38d8d5ac892190b0a (do not edit this line) */
