/* Generated By:JJTree: Do not edit this line. ASTCLASS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLASS extends SimpleNode {
  public ASTCLASS(int id) {
    super(id);
  }

  public ASTCLASS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a2baf7723dd7e594946ca38167eafcc (do not edit this line) */
