/* Generated By:JJTree: Do not edit this line. ASTCALL_ARGUMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL_ARGUMENTS extends SimpleNode {
  public ASTCALL_ARGUMENTS(int id) {
    super(id);
  }

  public ASTCALL_ARGUMENTS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5695dec51c8f336a3f3dbe38d8aaa802 (do not edit this line) */
