/* Generated By:JJTree: Do not edit this line. ASTCALL_ARGUMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL_ARGUMENTS extends SimpleNode {
  public ASTCALL_ARGUMENTS(int id) {
    super(id);
  }

  public ASTCALL_ARGUMENTS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3a6a3c9740242518f7c54a47ac5d204 (do not edit this line) */
