/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f761e217fb2076153629922d8656685 (do not edit this line) */
