/* Generated By:JJTree: Do not edit this line. ASTCLASS_NAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLASS_NAME extends SimpleNode {
  public ASTCLASS_NAME(int id) {
    super(id);
  }

  public ASTCLASS_NAME(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16eaa214ec81dfb0df50bb97a098741f (do not edit this line) */
