/* Generated By:JJTree: Do not edit this line. ASTCALL_FUNCTION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL_FUNCTION extends SimpleNode {
  public ASTCALL_FUNCTION(int id) {
    super(id);
  }

  public ASTCALL_FUNCTION(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=875f6fcab4615e6d33d71275ff5e2971 (do not edit this line) */
