/* Generated By:JJTree: Do not edit this line. ASTDOT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDOT extends SimpleNode {
  public ASTDOT(int id) {
    super(id);
  }

  public ASTDOT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0feac2da8a5a396eee4f0d89819481db (do not edit this line) */
