/* Generated By:JJTree: Do not edit this line. ASTELSE_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE_BODY extends SimpleNode {
  public ASTELSE_BODY(int id) {
    super(id);
  }

  public ASTELSE_BODY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ee892775f5258b84d03c8d42f778e10 (do not edit this line) */
