/* Generated By:JJTree: Do not edit this line. ASTExpression1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression1 extends SimpleNode {
  public ASTExpression1(int id) {
    super(id);
  }

  public ASTExpression1(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=552cf1c6667cf63799ce603cabf23596 (do not edit this line) */
