/* Generated By:JJTree: Do not edit this line. ASTExpression6.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression6 extends SimpleNode {
  public ASTExpression6(int id) {
    super(id);
  }

  public ASTExpression6(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95005b162af57d4591b671f14d1d7719 (do not edit this line) */
