/* Generated By:JJTree: Do not edit this line. ASTELSE_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE_BODY extends SimpleNode {
  public ASTELSE_BODY(int id) {
    super(id);
  }

  public ASTELSE_BODY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b01862114a19f6386e9c8b54cf5f84c (do not edit this line) */
