/* Generated By:JJTree: Do not edit this line. ASTExpression2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression2 extends SimpleNode {
  public ASTExpression2(int id) {
    super(id);
  }

  public ASTExpression2(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec8f4502d868cf97c10975bd60ef145f (do not edit this line) */
