/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5052667f415ac9db4bd1b0b21fba1ce (do not edit this line) */
