/* Generated By:JJTree: Do not edit this line. ASTIF_ELSE_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_ELSE_STATEMENT extends SimpleNode {
  public ASTIF_ELSE_STATEMENT(int id) {
    super(id);
  }

  public ASTIF_ELSE_STATEMENT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce8c39fdc48bbe9cf9518a236bf9dc53 (do not edit this line) */
