/* Generated By:JJTree: Do not edit this line. ASTID.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTID extends SimpleNode {
  public ASTID(int id) {
    super(id);
  }

  public ASTID(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ce3ea2e8ea1b2f4f5f3067f454fe0f4 (do not edit this line) */
