/* Generated By:JJTree: Do not edit this line. ASTINDEX.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINDEX extends SimpleNode {
  public ASTINDEX(int id) {
    super(id);
  }

  public ASTINDEX(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a0c0642f5e6b652543267ccbcc232e2 (do not edit this line) */
