/* Generated By:JJTree: Do not edit this line. ASTIF_ELSE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_ELSE extends SimpleNode {
  public ASTIF_ELSE(int id) {
    super(id);
  }

  public ASTIF_ELSE(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b7da6619dfd8dac2f0978a47b2e0207 (do not edit this line) */
