/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIDENTIFIER extends SimpleNode {
  public ASTIDENTIFIER(int id) {
    super(id);
  }

  public ASTIDENTIFIER(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36d3fcd5bf65ffdb04040392fa62dadb (do not edit this line) */
