/* Generated By:JJTree: Do not edit this line. ASTIF_ELSE_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_ELSE_STATEMENT extends SimpleNode {
  public ASTIF_ELSE_STATEMENT(int id) {
    super(id);
  }

  public ASTIF_ELSE_STATEMENT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a22c9d848f1fcf50e699008a4d940d6a (do not edit this line) */
