/* Generated By:JJTree: Do not edit this line. ASTIf_Else_Statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIf_Else_Statement extends SimpleNode {
  public ASTIf_Else_Statement(int id) {
    super(id);
  }

  public ASTIf_Else_Statement(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8cded32ec5f2f940dc89f828bc01ded3 (do not edit this line) */
