/* Generated By:JJTree: Do not edit this line. ASTINT_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINT_ARRAY extends SimpleNode {
  public ASTINT_ARRAY(int id) {
    super(id);
  }

  public ASTINT_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30cf30a9638f982957800a1bc77bbf31 (do not edit this line) */
