/* Generated By:JJTree: Do not edit this line. ASTINT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINT extends SimpleNode {
  public ASTINT(int id) {
    super(id);
  }

  public ASTINT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a7c09d3f7b3b75d9e031b2e2ce6f618 (do not edit this line) */
