/* Generated By:JJTree: Do not edit this line. ASTLENGTH.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLENGTH extends SimpleNode {
  public ASTLENGTH(int id) {
    super(id);
  }

  public ASTLENGTH(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efcf74dbc5811953df582068be418b98 (do not edit this line) */
