/* Generated By:JJTree: Do not edit this line. ASTMAIN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAIN extends SimpleNode {
  public ASTMAIN(int id) {
    super(id);
  }

  public ASTMAIN(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40340cf834030cbf9422206d1531f0fa (do not edit this line) */
