/* Generated By:JJTree: Do not edit this line. ASTMETHOD_ARGS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD_ARGS extends SimpleNode {
  public ASTMETHOD_ARGS(int id) {
    super(id);
  }

  public ASTMETHOD_ARGS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2aabc75df0e32a8a8f2cf594fe119fea (do not edit this line) */
