/* Generated By:JJTree: Do not edit this line. ASTMETHODS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHODS extends SimpleNode {
  public ASTMETHODS(int id) {
    super(id);
  }

  public ASTMETHODS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ed6ad0c604bbf9c6b40b5b25f563230 (do not edit this line) */
