/* Generated By:JJTree: Do not edit this line. ASTMAIN_METHOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAIN_METHOD extends SimpleNode {
  public ASTMAIN_METHOD(int id) {
    super(id);
  }

  public ASTMAIN_METHOD(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da6b00c65ca3b2349f8488d968a1e05b (do not edit this line) */
