/* Generated By:JJTree: Do not edit this line. ASTMUL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMUL extends SimpleNode {
  public ASTMUL(int id) {
    super(id);
  }

  public ASTMUL(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f9367400619d3bb2b3064661b68e5d4 (do not edit this line) */
