/* Generated By:JJTree: Do not edit this line. ASTMETHODS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHODS extends SimpleNode {
  public ASTMETHODS(int id) {
    super(id);
  }

  public ASTMETHODS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49f59aa46c2ffb11a243d17d66767bb7 (do not edit this line) */
