/* Generated By:JJTree: Do not edit this line. ASTMAIN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAIN extends SimpleNode {
  public ASTMAIN(int id) {
    super(id);
  }

  public ASTMAIN(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d154e77c8ba9c33486719ee38624f82 (do not edit this line) */
