/* Generated By:JJTree: Do not edit this line. ASTMULTIPLE_STATEMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMULTIPLE_STATEMENTS extends SimpleNode {
  public ASTMULTIPLE_STATEMENTS(int id) {
    super(id);
  }

  public ASTMULTIPLE_STATEMENTS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a7ff3ae98d3471302c2f04915d438ac6 (do not edit this line) */
