/* Generated By:JJTree: Do not edit this line. ASTMETHOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD extends SimpleNode {
  public ASTMETHOD(int id) {
    super(id);
  }

  public ASTMETHOD(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfb38197311d6244eb8775fef9bc2cb9 (do not edit this line) */
