/* Generated By:JJTree: Do not edit this line. ASTNEW_INT_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_INT_ARRAY extends SimpleNode {
  public ASTNEW_INT_ARRAY(int id) {
    super(id);
  }

  public ASTNEW_INT_ARRAY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=238eb9ab90c31ad307b72f52708488d2 (do not edit this line) */
