/* Generated By:JJTree: Do not edit this line. ASTNAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNAME extends SimpleNode {
  public ASTNAME(int id) {
    super(id);
  }

  public ASTNAME(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ff84731c60cf7250b06306647a2f3c2 (do not edit this line) */
