/* Generated By:JJTree: Do not edit this line. ASTNEW_CLASS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_CLASS extends SimpleNode {
  public ASTNEW_CLASS(int id) {
    super(id);
  }

  public ASTNEW_CLASS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee35accb64c4072c7d0d0b19358e2f51 (do not edit this line) */
