/* Generated By:JJTree: Do not edit this line. ASTNAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNAME extends SimpleNode {
  public ASTNAME(int id) {
    super(id);
  }

  public ASTNAME(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69ad130d939511d0f7ba41f91bdefb94 (do not edit this line) */
