/* Generated By:JJTree: Do not edit this line. ASTNOT_EX.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOT_EX extends SimpleNode {
  public ASTNOT_EX(int id) {
    super(id);
  }

  public ASTNOT_EX(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=688316efbc19ce5a44ac73959592fb0b (do not edit this line) */
