/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0e183ff54c4baed194fb4df39a83c6f (do not edit this line) */
