/* Generated By:JJTree: Do not edit this line. ASTNOT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOT extends SimpleNode {
  public ASTNOT(int id) {
    super(id);
  }

  public ASTNOT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bd722e957a24904d46cd008902ac9b9 (do not edit this line) */
