/* Generated By:JJTree: Do not edit this line. ASTRETURN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURN extends SimpleNode {
  public ASTRETURN(int id) {
    super(id);
  }

  public ASTRETURN(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6fa2ab72669b925bb06985833957d103 (do not edit this line) */
