/* Generated By:JJTree: Do not edit this line. ASTStatement_1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_1 extends SimpleNode {
  public ASTStatement_1(int id) {
    super(id);
  }

  public ASTStatement_1(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=78ca64b328c1bab4259af775cdb64b59 (do not edit this line) */
