/* Generated By:JJTree: Do not edit this line. ASTSTATEMENTS_.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENTS_ extends SimpleNode {
  public ASTSTATEMENTS_(int id) {
    super(id);
  }

  public ASTSTATEMENTS_(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2793f52d006c3b94afb1e28fda5efa12 (do not edit this line) */
