/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT_DECLS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT_DECLS extends SimpleNode {
  public ASTSTATEMENT_DECLS(int id) {
    super(id);
  }

  public ASTSTATEMENT_DECLS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2586054bfa97cdf2122da3390e50b8aa (do not edit this line) */
