/* Generated By:JJTree: Do not edit this line. ASTStatement2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement2 extends SimpleNode {
  public ASTStatement2(int id) {
    super(id);
  }

  public ASTStatement2(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f04b7fbfc5a6b81935629977070d2c10 (do not edit this line) */
