/* Generated By:JJTree: Do not edit this line. ASTStatement1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement1 extends SimpleNode {
  public ASTStatement1(int id) {
    super(id);
  }

  public ASTStatement1(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcbaf33735b6ffd3de4bd93599983814 (do not edit this line) */
