/* Generated By:JJTree: Do not edit this line. ASTSTATEMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENTS extends SimpleNode {
  public ASTSTATEMENTS(int id) {
    super(id);
  }

  public ASTSTATEMENTS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df464b6edc05e1c0ff1dc81528c44428 (do not edit this line) */
