/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT extends SimpleNode {
  public ASTSTATEMENT(int id) {
    super(id);
  }

  public ASTSTATEMENT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=111943a1e17c8b2f7b9bdfadc6af59f0 (do not edit this line) */
