/* Generated By:JJTree: Do not edit this line. ASTStatements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatements extends SimpleNode {
  public ASTStatements(int id) {
    super(id);
  }

  public ASTStatements(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64ccc46e3f088688eb93154e7f6db3dd (do not edit this line) */
