/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT_LIST extends SimpleNode {
  public ASTSTATEMENT_LIST(int id) {
    super(id);
  }

  public ASTSTATEMENT_LIST(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e73713738104fb69c16c30eef779e352 (do not edit this line) */
