/* Generated By:JJTree: Do not edit this line. ASTTHIS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTHIS extends SimpleNode {
  public ASTTHIS(int id) {
    super(id);
  }

  public ASTTHIS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8058181242a0d5725260f0c39c203baf (do not edit this line) */
