/* Generated By:JJTree: Do not edit this line. ASTVAR_DECLS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR_DECLS extends SimpleNode {
  public ASTVAR_DECLS(int id) {
    super(id);
  }

  public ASTVAR_DECLS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b85b0901a4354f2646ebf82f6ae94fbe (do not edit this line) */
