/* Generated By:JJTree: Do not edit this line. ASTVARS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVARS extends SimpleNode {
  public ASTVARS(int id) {
    super(id);
  }

  public ASTVARS(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5fb35abd98a7e5aced120793e76c991f (do not edit this line) */
