/* Generated By:JJTree: Do not edit this line. ASTVAR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR extends SimpleNode {
  public ASTVAR(int id) {
    super(id);
  }

  public ASTVAR(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bde14370afee056cfa475cb0928087e9 (do not edit this line) */
