/* Generated By:JJTree: Do not edit this line. ASTVarDec_Stat.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDec_Stat extends SimpleNode {
  public ASTVarDec_Stat(int id) {
    super(id);
  }

  public ASTVarDec_Stat(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9a5ba4f71615e69cc66ef4cdb69826b (do not edit this line) */
