/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration_1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration_1 extends SimpleNode {
  public ASTVarDeclaration_1(int id) {
    super(id);
  }

  public ASTVarDeclaration_1(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efb85478fc2fbe8538aa6fc78f9b7026 (do not edit this line) */
