/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89a328c88093b14ebf1f1607c48f361c (do not edit this line) */
