/* Generated By:JJTree: Do not edit this line. ASTWHILE_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE_BODY extends SimpleNode {
  public ASTWHILE_BODY(int id) {
    super(id);
  }

  public ASTWHILE_BODY(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e474dc246a5ad78d4f349d087c2bc75d (do not edit this line) */
