/* Generated By:JJTree: Do not edit this line. ASTWhile_Statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile_Statement extends SimpleNode {
  public ASTWhile_Statement(int id) {
    super(id);
  }

  public ASTWhile_Statement(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a50f0a37a2228c6fc7d0e633d7f8a17c (do not edit this line) */
