/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31b550908a24355d98a780f86e1334e3 (do not edit this line) */
