/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 6.0_1 */
public interface jmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTCLASS_NAME = 2;
  public int JJTCLASS = 3;
  public int JJTCLASS_EXTENDS = 4;
  public int JJTEXTENDED_CLASS = 5;
  public int JJTMETHODS = 6;
  public int JJTVAR_DECLS = 7;
  public int JJTVAR_DECL = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTMETHOD_BODY = 10;
  public int JJTMAIN = 11;
  public int JJTARGV = 12;
  public int JJTMETHOD = 13;
  public int JJTNAME = 14;
  public int JJTMETHOD_ARGS = 15;
  public int JJTARG = 16;
  public int JJTINT = 17;
  public int JJTINT_ARRAY = 18;
  public int JJTBOOLEAN = 19;
  public int JJTSTATEMENT_LIST = 20;
  public int JJTIF_ELSE = 21;
  public int JJTWHILE = 22;
  public int JJTASSIGN = 23;
  public int JJTACCESS_ARRAY = 24;
  public int JJTASSIGN_ARRAY = 25;
  public int JJTTRUE = 26;
  public int JJTFALSE = 27;
  public int JJTTHIS = 28;
  public int JJTNOT = 29;
  public int JJTNEW_INT_ARRAY = 30;
  public int JJTNEW_CLASS = 31;
  public int JJTAND = 32;
  public int JJTLT = 33;
  public int JJTADD = 34;
  public int JJTSUB = 35;
  public int JJTMUL = 36;
  public int JJTDIV = 37;
  public int JJTLENGTH = 38;
  public int JJTFUNCTION = 39;
  public int JJTCALL_FUNCTION = 40;
  public int JJTCALL_ARGUMENTS = 41;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "CLASS_NAME",
    "CLASS",
    "CLASS_EXTENDS",
    "EXTENDED_CLASS",
    "METHODS",
    "VAR_DECLS",
    "VAR_DECL",
    "IDENTIFIER",
    "METHOD_BODY",
    "MAIN",
    "ARGV",
    "METHOD",
    "NAME",
    "METHOD_ARGS",
    "ARG",
    "INT",
    "INT_ARRAY",
    "BOOLEAN",
    "STATEMENT_LIST",
    "IF_ELSE",
    "WHILE",
    "ASSIGN",
    "ACCESS_ARRAY",
    "ASSIGN_ARRAY",
    "TRUE",
    "FALSE",
    "THIS",
    "NOT",
    "NEW_INT_ARRAY",
    "NEW_CLASS",
    "AND",
    "LT",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "LENGTH",
    "FUNCTION",
    "CALL_FUNCTION",
    "CALL_ARGUMENTS",
  };
}
/* JavaCC - OriginalChecksum=5b3fd9c90522d49797b16fe0d17c5185 (do not edit this line) */
