/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 6.0_1 */
public interface jmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTCLASS_NAME = 2;
  public int JJTCLASS = 3;
  public int JJTCLASS_EXTENDS = 4;
  public int JJTEXTENDED_CLASS = 5;
  public int JJTMETHODS = 6;
  public int JJTVAR_DECLS = 7;
  public int JJTVAR_DECL = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTMETHOD_BODY = 10;
  public int JJTMAIN = 11;
  public int JJTARGV = 12;
  public int JJTMETHOD = 13;
  public int JJTNAME = 14;
  public int JJTRETURN_EXPRESSION = 15;
  public int JJTMETHOD_ARGS = 16;
  public int JJTARG = 17;
  public int JJTINT = 18;
  public int JJTINT_ARRAY = 19;
  public int JJTBOOLEAN = 20;
  public int JJTSTATEMENT_LIST = 21;
  public int JJTIF_ELSE = 22;
  public int JJTWHILE = 23;
  public int JJTASSIGN = 24;
  public int JJTACCESS_ARRAY = 25;
  public int JJTASSIGN_ARRAY = 26;
  public int JJTTRUE = 27;
  public int JJTFALSE = 28;
  public int JJTTHIS = 29;
  public int JJTNOT = 30;
  public int JJTNEW_INT_ARRAY = 31;
  public int JJTNEW_CLASS = 32;
  public int JJTAND = 33;
  public int JJTLT = 34;
  public int JJTADD = 35;
  public int JJTSUB = 36;
  public int JJTMUL = 37;
  public int JJTDIV = 38;
  public int JJTLENGTH = 39;
  public int JJTFUNCTION = 40;
  public int JJTCALL_FUNCTION = 41;
  public int JJTCALL_ARGUMENTS = 42;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "CLASS_NAME",
    "CLASS",
    "CLASS_EXTENDS",
    "EXTENDED_CLASS",
    "METHODS",
    "VAR_DECLS",
    "VAR_DECL",
    "IDENTIFIER",
    "METHOD_BODY",
    "MAIN",
    "ARGV",
    "METHOD",
    "NAME",
    "RETURN_EXPRESSION",
    "METHOD_ARGS",
    "ARG",
    "INT",
    "INT_ARRAY",
    "BOOLEAN",
    "STATEMENT_LIST",
    "IF_ELSE",
    "WHILE",
    "ASSIGN",
    "ACCESS_ARRAY",
    "ASSIGN_ARRAY",
    "TRUE",
    "FALSE",
    "THIS",
    "NOT",
    "NEW_INT_ARRAY",
    "NEW_CLASS",
    "AND",
    "LT",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "LENGTH",
    "FUNCTION",
    "CALL_FUNCTION",
    "CALL_ARGUMENTS",
  };
}
/* JavaCC - OriginalChecksum=5025f38d1bff91b9dd99c83c6cff3503 (do not edit this line) */
