/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTASSIGN extends SimpleNode {
  public ASTASSIGN(int id) {
    super(id);
  }

  public ASTASSIGN(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5eb504e5d2ae7d4f22071d6da182b4fa (do not edit this line) */
