/* Generated By:JJTree: Do not edit this line. ASTARG.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTARG extends SimpleNode {
  public ASTARG(int id) {
    super(id);
  }

  public ASTARG(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f5cd04c459e9982553b118961980ae4 (do not edit this line) */
