/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAND extends SimpleNode {
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=057ec119c84f2e0e6120bc3875ad89e8 (do not edit this line) */
