/* Generated By:JJTree: Do not edit this line. ASTASSIGN_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTASSIGN_ARRAY extends SimpleNode {
  public ASTASSIGN_ARRAY(int id) {
    super(id);
  }

  public ASTASSIGN_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01f620270a21339b758ba68f5eaa317a (do not edit this line) */
