/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTADD extends SimpleNode {
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=80231333de6ecbbdef2abb66576f0eeb (do not edit this line) */
