/* Generated By:JJTree: Do not edit this line. ASTARGV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTARGV extends SimpleNode {
  public ASTARGV(int id) {
    super(id);
  }

  public ASTARGV(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a23a9efa116bc1c0121df1d51a36f3a (do not edit this line) */
