/* Generated By:JJTree: Do not edit this line. ASTACCESS_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTACCESS_ARRAY extends SimpleNode {
  public ASTACCESS_ARRAY(int id) {
    super(id);
  }

  public ASTACCESS_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b1029f2daf55f599796d374c4c2c3c9 (do not edit this line) */
