/* Generated By:JJTree: Do not edit this line. ASTASSIGN_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGN_ARRAY extends SimpleNode {
  public ASTASSIGN_ARRAY(int id) {
    super(id);
  }

  public ASTASSIGN_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a787e831d88cfa41211630adeeeb2560 (do not edit this line) */
