/* Generated By:JJTree: Do not edit this line. ASTBOOLEAN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOLEAN extends SimpleNode {
  public ASTBOOLEAN(int id) {
    super(id);
  }

  public ASTBOOLEAN(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5dce9e906e428e3ba6c68bd890655b10 (do not edit this line) */
