/* Generated By:JJTree: Do not edit this line. ASTCLASS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCLASS extends SimpleNode {
  public ASTCLASS(int id) {
    super(id);
  }

  public ASTCLASS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa4fbb12148c5c98e0a21f1cf53b1068 (do not edit this line) */
