/* Generated By:JJTree: Do not edit this line. ASTCLASS_NAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLASS_NAME extends SimpleNode {
  public ASTCLASS_NAME(int id) {
    super(id);
  }

  public ASTCLASS_NAME(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7b5362f3063e9af4a45c7f739763dea (do not edit this line) */
