/* Generated By:JJTree: Do not edit this line. ASTCALL_FUNCTION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL_FUNCTION extends SimpleNode {
  public ASTCALL_FUNCTION(int id) {
    super(id);
  }

  public ASTCALL_FUNCTION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47c74f44551c159ba619c12adca1c225 (do not edit this line) */
