/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5593a7b00fd0a0fab36d87b36b29a1ea (do not edit this line) */
