/* Generated By:JJTree: Do not edit this line. ASTCALL_FUNCTION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCALL_FUNCTION extends SimpleNode {
  public ASTCALL_FUNCTION(int id) {
    super(id);
  }

  public ASTCALL_FUNCTION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5a48833b6a8f6fbd23c13edb04a3c51 (do not edit this line) */
