/* Generated By:JJTree: Do not edit this line. ASTCLASS_NAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCLASS_NAME extends SimpleNode {
  public ASTCLASS_NAME(int id) {
    super(id);
  }

  public ASTCLASS_NAME(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e1edcf2edaf8bbca61e5f135b70ec74 (do not edit this line) */
