/* Generated By:JJTree: Do not edit this line. ASTCLASS_EXTENDS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCLASS_EXTENDS extends SimpleNode {
  public ASTCLASS_EXTENDS(int id) {
    super(id);
  }

  public ASTCLASS_EXTENDS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d066f6152a00be1984000c857451fa5 (do not edit this line) */
