/* Generated By:JJTree: Do not edit this line. ASTDIV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDIV extends SimpleNode {
  public ASTDIV(int id) {
    super(id);
  }

  public ASTDIV(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5208535b4942a4fe1901667a51ea00f0 (do not edit this line) */
