/* Generated By:JJTree: Do not edit this line. ASTEXTENDED_CLASS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXTENDED_CLASS extends SimpleNode {
  public ASTEXTENDED_CLASS(int id) {
    super(id);
  }

  public ASTEXTENDED_CLASS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=387123b06bddecd788fec27a4a2127d6 (do not edit this line) */
