/* Generated By:JJTree: Do not edit this line. ASTFUNCTION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFUNCTION extends SimpleNode {
  public ASTFUNCTION(int id) {
    super(id);
  }

  public ASTFUNCTION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab1a1b9d95ab04449f3fe85d0525008a (do not edit this line) */
