/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=adc6671b2a4144cf2e858d9739c50d5d (do not edit this line) */
