/* Generated By:JJTree: Do not edit this line. ASTIF_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIF_BODY extends SimpleNode {
  public ASTIF_BODY(int id) {
    super(id);
  }

  public ASTIF_BODY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c1a67c02f9af5aae9d795ded58f2721 (do not edit this line) */
