/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIDENTIFIER extends SimpleNode {
  public ASTIDENTIFIER(int id) {
    super(id);
  }

  public ASTIDENTIFIER(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=371a25bc7f36ba6dce767c0648c76e7b (do not edit this line) */
