/* Generated By:JJTree: Do not edit this line. ASTIF_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_BODY extends SimpleNode {
  public ASTIF_BODY(int id) {
    super(id);
  }

  public ASTIF_BODY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0386f14650f4799b021bce9a747c65fb (do not edit this line) */
