/* Generated By:JJTree: Do not edit this line. ASTINT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTINT extends SimpleNode {
  public ASTINT(int id) {
    super(id);
  }

  public ASTINT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6ba4158a6a0aed125c7b6eed5b4a67e (do not edit this line) */
