/* Generated By:JJTree: Do not edit this line. ASTIF_ELSE_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIF_ELSE_STATEMENT extends SimpleNode {
  public ASTIF_ELSE_STATEMENT(int id) {
    super(id);
  }

  public ASTIF_ELSE_STATEMENT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29f6b7758b1a3a090af4070e8bd7e876 (do not edit this line) */
