/* Generated By:JJTree: Do not edit this line. ASTINT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINT extends SimpleNode {
  public ASTINT(int id) {
    super(id);
  }

  public ASTINT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c62c554a4cf4a0be9248be02161b858 (do not edit this line) */
