/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de72064389e20d71410ca6bd1a0d6775 (do not edit this line) */
