/* Generated By:JJTree: Do not edit this line. ASTLENGTH.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTLENGTH extends SimpleNode {
  public ASTLENGTH(int id) {
    super(id);
  }

  public ASTLENGTH(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0166f60766968aa84d28b00d6d814d9d (do not edit this line) */
