/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3caaa143bdfc64da8bd6b204044b4104 (do not edit this line) */
