/* Generated By:JJTree: Do not edit this line. ASTMETHOD_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD_BODY extends SimpleNode {
  public ASTMETHOD_BODY(int id) {
    super(id);
  }

  public ASTMETHOD_BODY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e74d2c742607bc53ada8cad9ff6888e7 (do not edit this line) */
