/* Generated By:JJTree: Do not edit this line. ASTMETHOD_BODY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMETHOD_BODY extends SimpleNode {
  public ASTMETHOD_BODY(int id) {
    super(id);
  }

  public ASTMETHOD_BODY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=172793f5f9169f35653254a42f5e728e (do not edit this line) */
