/* Generated By:JJTree: Do not edit this line. ASTMETHODS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMETHODS extends SimpleNode {
  public ASTMETHODS(int id) {
    super(id);
  }

  public ASTMETHODS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0333391e580d2e094a30e00a2a89e3c1 (do not edit this line) */
