/* Generated By:JJTree: Do not edit this line. ASTMETHOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMETHOD extends SimpleNode {
  public ASTMETHOD(int id) {
    super(id);
  }

  public ASTMETHOD(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d431346d19a9a16b57a3f417f45550b (do not edit this line) */
