/* Generated By:JJTree: Do not edit this line. ASTMUL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMUL extends SimpleNode {
  public ASTMUL(int id) {
    super(id);
  }

  public ASTMUL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2b85c7efaae83283827a67d8f328bbf (do not edit this line) */
