/* Generated By:JJTree: Do not edit this line. ASTMETHOD_ARGS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMETHOD_ARGS extends SimpleNode {
  public ASTMETHOD_ARGS(int id) {
    super(id);
  }

  public ASTMETHOD_ARGS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90cbe913f4d16f6f9a506bfb313e64df (do not edit this line) */
