/* Generated By:JJTree: Do not edit this line. ASTNOT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNOT extends SimpleNode {
  public ASTNOT(int id) {
    super(id);
  }

  public ASTNOT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30f1676227c04c04121dc8c8ed911d1d (do not edit this line) */
