/* Generated By:JJTree: Do not edit this line. ASTNEW_INT_ARRAY.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_INT_ARRAY extends SimpleNode {
  public ASTNEW_INT_ARRAY(int id) {
    super(id);
  }

  public ASTNEW_INT_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e63fb02b1e326ba1e0b5a9c70985599 (do not edit this line) */
