/* Generated By:JJTree: Do not edit this line. ASTNAME.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNAME extends SimpleNode {
  public ASTNAME(int id) {
    super(id);
  }

  public ASTNAME(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fbc6ae5db413d4366fd2e39bd8b1c062 (do not edit this line) */
