/* Generated By:JJTree: Do not edit this line. ASTNEW_CLASS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNEW_CLASS extends SimpleNode {
  public ASTNEW_CLASS(int id) {
    super(id);
  }

  public ASTNEW_CLASS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7d803a741770ac06401849cada61ebb (do not edit this line) */
