/* Generated By:JJTree: Do not edit this line. ASTRETURN_EXPRESSION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRETURN_EXPRESSION extends SimpleNode {
  public ASTRETURN_EXPRESSION(int id) {
    super(id);
  }

  public ASTRETURN_EXPRESSION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ec7e97e3e4421be1e78986e6b8a93bc (do not edit this line) */
