/* Generated By:JJTree: Do not edit this line. ASTSUB.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSUB extends SimpleNode {
  public ASTSUB(int id) {
    super(id);
  }

  public ASTSUB(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9b2065d596205b527240c53c6f50541 (do not edit this line) */
