/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSTATEMENT_LIST extends SimpleNode {
  public ASTSTATEMENT_LIST(int id) {
    super(id);
  }

  public ASTSTATEMENT_LIST(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14a695e563c536310f97045b74f91159 (do not edit this line) */
