/* Generated By:JJTree: Do not edit this line. ASTTHIS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTHIS extends SimpleNode {
  public ASTTHIS(int id) {
    super(id);
  }

  public ASTTHIS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=33325217248303e58ea9635a9d9860ee (do not edit this line) */
