/* Generated By:JJTree: Do not edit this line. ASTTRUE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTRUE extends SimpleNode {
  public ASTTRUE(int id) {
    super(id);
  }

  public ASTTRUE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc6eb2e644bdf553169b1b774f0ebe42 (do not edit this line) */
