/* Generated By:JJTree: Do not edit this line. ASTVAR_DECL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR_DECL extends SimpleNode {
  public ASTVAR_DECL(int id) {
    super(id);
  }

  public ASTVAR_DECL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f868be57eeb25ec544a807723e6d49cb (do not edit this line) */
