/* Generated By:JJTree: Do not edit this line. ASTVAR_DECLS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTVAR_DECLS extends SimpleNode {
  public ASTVAR_DECLS(int id) {
    super(id);
  }

  public ASTVAR_DECLS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c84c5ce5b36dbd5e2b68048c6f99a2aa (do not edit this line) */
