/* Generated By:JJTree: Do not edit this line. ASTVAR_DECLS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR_DECLS extends SimpleNode {
  public ASTVAR_DECLS(int id) {
    super(id);
  }

  public ASTVAR_DECLS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22ab1384bed9618b7fe247a2004230b7 (do not edit this line) */
