/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aa03f1ebff7d438acd6c95cddd4bd1f7 (do not edit this line) */
