/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTCLASS_NAME = 2;
  public int JJTCLASS = 3;
  public int JJTCLASS_EXTENDS = 4;
  public int JJTEXTENDED_CLASS = 5;
  public int JJTMETHODS = 6;
  public int JJTVAR_DECLS = 7;
  public int JJTVAR_DECL = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTMETHOD_BODY = 10;
  public int JJTMAIN = 11;
  public int JJTARGV = 12;
  public int JJTMETHOD = 13;
  public int JJTNAME = 14;
  public int JJTRETURN_EXPRESSION = 15;
  public int JJTMETHOD_ARGS = 16;
  public int JJTARG = 17;
  public int JJTINT = 18;
  public int JJTINT_ARRAY = 19;
  public int JJTBOOLEAN = 20;
  public int JJTSTATEMENT_LIST = 21;
  public int JJTIF_ELSE_STATEMENT = 22;
  public int JJTCONDITION = 23;
  public int JJTIF_BODY = 24;
  public int JJTELSE_BODY = 25;
  public int JJTWHILE = 26;
  public int JJTWHILE_BODY = 27;
  public int JJTASSIGN = 28;
  public int JJTACCESS_ARRAY = 29;
  public int JJTASSIGN_ARRAY = 30;
  public int JJTTRUE = 31;
  public int JJTFALSE = 32;
  public int JJTTHIS = 33;
  public int JJTNOT = 34;
  public int JJTNEW_INT_ARRAY = 35;
  public int JJTNEW_CLASS = 36;
  public int JJTAND = 37;
  public int JJTLT = 38;
  public int JJTADD = 39;
  public int JJTSUB = 40;
  public int JJTMUL = 41;
  public int JJTDIV = 42;
  public int JJTLENGTH = 43;
  public int JJTFUNCTION = 44;
  public int JJTCALL_FUNCTION = 45;
  public int JJTCALL_ARGUMENTS = 46;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "CLASS_NAME",
    "CLASS",
    "CLASS_EXTENDS",
    "EXTENDED_CLASS",
    "METHODS",
    "VAR_DECLS",
    "VAR_DECL",
    "IDENTIFIER",
    "METHOD_BODY",
    "MAIN",
    "ARGV",
    "METHOD",
    "NAME",
    "RETURN_EXPRESSION",
    "METHOD_ARGS",
    "ARG",
    "INT",
    "INT_ARRAY",
    "BOOLEAN",
    "STATEMENT_LIST",
    "IF_ELSE_STATEMENT",
    "CONDITION",
    "IF_BODY",
    "ELSE_BODY",
    "WHILE",
    "WHILE_BODY",
    "ASSIGN",
    "ACCESS_ARRAY",
    "ASSIGN_ARRAY",
    "TRUE",
    "FALSE",
    "THIS",
    "NOT",
    "NEW_INT_ARRAY",
    "NEW_CLASS",
    "AND",
    "LT",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "LENGTH",
    "FUNCTION",
    "CALL_FUNCTION",
    "CALL_ARGUMENTS",
  };
}
/* JavaCC - OriginalChecksum=1b1eb50a9cd32eb795c58bce01b18d2f (do not edit this line) */
